apiVersion: v1
kind: Service
metadata:
  name: aggregator
  labels:
    app: aggregator
spec:
  type: NodePort
  ports:
  - name: grpc
    port: 11000
    targetPort: grpc
  selector:
    app: aggregator
